### ISSUE TITLE
iOS下载后，运行不了

### ISSUE THREAD

**Issue by developerjet** [yubo725/flutter-osc#13]
请问下载源码后，需要进行哪些相关的配置吗？

**Comment by yubo725** [comment]
iOS没有提供下载，需要自己编译源码，直接导入代码到AS中即可，如果Flutter环境装得没问题，不需要其他配置

**Comment by littlepriest** [comment]
@yubo725 跑那个sh脚本？可是因为 flutter.framework 的缺失，导致ERROR: Unknown FLUTTER_BUILD_MODE 报错了。我强制改mode 为 debug，又报The path /bin/cache/artifacts/engine/ios does not exist

**Comment by yubo725** [comment]
装好AndroidStudio，配置好flutter开发环境，启动iOS模拟器，可直接运行，没有其他配置

**Comment by littlepriest** [comment]
@yubo725 嗯。。目前在死磕xcode,缺乏flutter.framework，实在不行用as吧。我比较担忧发布的事
