### ISSUE TITLE
xcode编译报flutter not found

### ISSUE THREAD

**Issue by Geforceyu** [yubo725/flutter-osc#15]
下载后在ios下运行报错，flutter not found请教如何解决

**Comment by yubo725** [comment]
flutter开发环境装了吗

**Comment by Geforceyu** [comment]
恩，我自己的工程都能运行

**Comment by Geforceyu** [comment]
用xcode打开，看到flutter.framework和app.framework文件都是红的，本地没有。podfile.lock和pods文件夹删除了，重新pod install试过也不行

**Comment by WuZhaogang** [comment]
同问

**Comment by GanZhiXiong** [comment]
卸载CocoaPods，安装CocoaPods v1.4
