### ISSUE TITLE
flutter run 后出现以下问题。。。

### ISSUE THREAD

**Issue by ryan730** [yubo725/flutter-osc#17]
flutter run 后出现以下问题。。。

Running "flutter packages get" in flutter_osc...                 
Because every version of flutter_test from sdk depends on csslib 0.14.5 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because flutter_osc depends on flutter_test any from sdk, version solving failed. 

使用翻墙也不行。。。

**Comment by yubo725** [comment]
代码已做更新

**Comment by end-with-hehe** [comment]
请问下flutter的热更新有什么办法吗，找了很多地方都没看到有热更新的功能
