### ISSUE TITLE
flutter run 失败：flutter_webview_plugin 0.1.6 requires SDK version >=1.19.0 <2.0.0

### ISSUE THREAD

**Issue by L2Mlee** [yubo725/flutter-osc#18]
报错：Because flutter_webview_plugin 0.1.6 requires SDK version >=1.19.0 <2.0.0 and no versions of flutter_webview_plugin match >0.1.6 <0.2.0, flutter_webview_plugin ^0.1.6 is forbidden.
So, because flutter_osc depends on flutter_webview_plugin ^0.1.6, version solving failed.

**Comment by ljxx** [comment]
> 报错：Because flutter_webview_plugin 0.1.6 requires SDK version >=1.19.0 <2.0.0 and no versions of flutter_webview_plugin match >0.1.6 <0.2.0, flutter_webview_plugin ^0.1.6 is forbidden.
> So, because flutter_osc depends on flutter_webview_plugin ^0.1.6, version solving failed.


update:
1、flutter_webview_plugin: ^0.2.0
2、event_bus: ^1.0.1

**Comment by MiYogurt** [comment]
and fix eventBus error .

```dart
    Constants.eventBus.on<LoginEvent>().listen((event) {
      setState(() {
        this.isUserLogin = true;
      });
    });
    Constants.eventBus.on<LogoutEvent>().listen((event) {
      setState(() {
        this.isUserLogin = false;
      });
    });
```

但是编译 pod install 还是有错 头文件找不到。

**Comment by MiYogurt** [comment]
然后阅读此 issus https://github.com/flutter/flutter/issues/22123

**Comment by MiYogurt** [comment]
运行还是比较多的 wanrning 和异常 webview 也不行，运行还是要稳定版。

**Comment by yubo725** [comment]
代码已做更新，升级了Flutter版本，可以重新拉代码再编译看看
