### ISSUE TITLE
android 上运行报错，iOS可以

### ISSUE THREAD

**Issue by Nealyang** [yubo725/flutter-osc#19]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "/Users/nealyang/Downloads/flutter-osc-master/android/gradlew" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':barcode_scan'.
> Could not resolve all files for configuration ':barcode_scan:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.4.
     Required by:
         project :barcode_scan
      > Could not resolve com.android.tools.build:gradle:3.1.4.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
            > Could not HEAD 'https://maven.google.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
               > Connect to maven.google.com:443 [maven.google.com/74.125.198.94, maven.google.com/2607:f8b0:4003:c05:0:0:0:5e] failed: No route to host (connect failed)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 38s
  Command: /Users/nealyang/Downloads/flutter-osc-master/android/gradlew app:properties
Please review your Gradle project setup in the android/ folder.

**Comment by Nealyang** [comment]
https://pub.dartlang.org/packages/barcode_scan

看你的源码里面并没有修改Android下的AndroidManifest.xml

**Comment by caiorngcai** [comment]
这个只要在hosts文件加谷歌的ip地址映射就可以了。

**Comment by yubo725** [comment]
这个是你的网络问题，与项目无关
