### ISSUE TITLE
一直显示Loading

### ISSUE THREAD

**Issue by cookiemouse** [yubo725/flutter-osc#2]
测试用例：
环境Android手机，华为P9；
1、打开flutter_osc应用，显示资讯；
2、点击Item(我点开的是Chrome将不再标记HTTPS页面为安全站点)，跳转到资讯详情页面；
3、点击页面中右上角的关闭按钮（应该是开源中国的广告），显示正常；
4、点击Android手机的Back键，显示Loading，一直不消失。

**Comment by yubo725** [comment]
重新试试，项目代码做了更新，也可能是你的网络环境问题，因为该项目的服务器部署在香港
