### ISSUE TITLE
没办法登录

### ISSUE THREAD

**Issue by QSKOBE24** [yubo725/flutter-osc#29]
登录页面，使用原生和Webview方式登录 一直都是在loadIng状态，无法登录。

**Comment by yubo725** [comment]
资讯列表刷得出来吗？

**Comment by QSKOBE24** [comment]
可以。但是就是没办法登录。而且我已经处于翻墙环境了。

**Comment by yubo725** [comment]
切换不同的网络看看，登录是走的OSC的，不用翻墙

**Comment by QSKOBE24** [comment]
![image](https://user-images.githubusercontent.com/5968595/50747382-952d7e80-126e-11e9-8798-8e7d872b5d93.png)
已经切换了不同的网络  还是不行

**Comment by yubo725** [comment]
可能有点问题，我查一下

**Comment by Rororororororororororororororororororo** [comment]
@QSKOBE24 @yubo725  我也是无法正常登陆，加载不出来。切换了30多条路由网络地址还是不行

**Comment by QSKOBE24** [comment]
一直有个这个问题。。。看了下代码，感觉也没啥大问题，不知道为啥一直登录中，请稍等

**Comment by Rororororororororororororororororororo** [comment]
@QSKOBE24 大兄弟 那你目前在看哪个demo学flutter

**Comment by yubo725** [comment]
登录的问题修了下，再看看能不能登录

**Comment by Rororororororororororororororororororo** [comment]
@yubo725 现在试了，并不行。老兄

**Comment by QSKOBE24** [comment]
还是一样不行！

**Comment by yubo725** [comment]
我这边测试没有问题

**Comment by meidong163** [comment]
我今天down代码下来也登不上去，不过没关系啦，先学习些首页

**Comment by Rororororororororororororororororororo** [comment]
@yubo725 http://osc.yubo725.top/news/list?pageIndex=1&pageSize=10 这个链接登录不进去了，老兄维护一下

**Comment by yusinan0119** [comment]
确实还是无法登录

**Comment by lovebzhou** [comment]
无法登录

**Comment by yubo725** [comment]
我这边测试登录是正常的，如果原生页面无法登录，改用WebView登录试试

**Comment by wwwang89** [comment]
APP同样 没法登陆哦。。。在电脑浏览器上面可以登录的，另外首页的咨询列表数据是写死的吗？我看到还是八月份的数据。。。@yubo725

**Comment by yubo725** [comment]
> APP同样 没法登陆哦。。。在电脑浏览器上面可以登录的，另外首页的咨询列表数据是写死的吗？我看到还是八月份的数据。。。@yubo725

首页数据是用python爬的，由于osc网站改版了，导致爬不到首页数据了，无法登录可以试试ping得通osc.yubo725.top吗，服务器在香港所以可能某些地方无法访问，我这边可以正常登录

**Comment by wwwang89** [comment]
> osc.yubo725.top

 ping osc.yubo725.top
PING osc.yubo725.top (104.31.70.76): 56 data bytes
64 bytes from 104.31.70.76: icmp_seq=0 ttl=49 time=509.933 ms
64 bytes from 104.31.70.76: icmp_seq=1 ttl=49 time=294.141 ms
64 bytes from 104.31.70.76: icmp_seq=2 ttl=49 time=220.488 ms
64 bytes from 104.31.70.76: icmp_seq=3 ttl=49 time=216.659 ms
64 bytes from 104.31.70.76: icmp_seq=4 ttl=49 time=216.428 ms

可以ping通，这么多人无法登录，感觉是不是有什么账户登录权限问题？

**Comment by Davisjy** [comment]
+1无法登陆

**Comment by yubo725** [comment]
目前接口部署在香港阿里云，访问比较慢，后面会迁到新的服务器上

**Comment by yubo725** [comment]
登录不了的朋友请扫码重新安装app试试看，服务器做了迁移，现在登录应该正常

**Comment by zinwalin** [comment]
还是无法登录 ， 最新的App
